export enum EOrderStatus {
    ORDERING = 'ORDERING',
    PAYMENT_PENDING = 'PAYMENT_PENDING',
    PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
    PREPARING = 'PREPARING',
    CANCELLED = 'CANCELLED',
    QUEUED = 'QUEUED',
    DONE = 'DONE',
}